# -*- coding: utf-8 -*-
"""Technical Event Management.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KlXhHezOr4G8WXQyjxF9X3uUftFLfOl7
"""

import getpass
from datetime import datetime, timedelta

admins = {"admin": "admin123"}
users = {}
memberships = {}
current_session = {"role": None, "username": None}

def clear_session():
    current_session["role"] = None
    current_session["username"] = None

def require_login(role):
    return current_session["role"] == role

def admin_login():
    u = input("Admin Username: ")
    p = getpass.getpass("Password: ")
    if admins.get(u) == p:
        current_session["role"] = "admin"
        current_session["username"] = u
        print("Admin login successful")
    else:
        print("Invalid admin credentials")

def user_signup():
    u = input("Username: ")
    if u in users:
        print("User already exists")
        return
    p = getpass.getpass("Password: ")
    users[u] = p
    print("User registered successfully")

def user_login():
    u = input("Username: ")
    p = getpass.getpass("Password: ")
    if users.get(u) == p:
        current_session["role"] = "user"
        current_session["username"] = u
        print("User login successful")
    else:
        print("Invalid user credentials")

def add_membership():
    print("\nAdd Membership (All fields mandatory)")
    name = input("Member Name: ")
    if not name:
        print("Name is mandatory")
        return

    print("Select Membership Duration:")
    print("1. 6 Months (Default)")
    print("2. 1 Year")
    print("3. 2 Years")

    choice = input("Choice: ") or "1"

    duration_map = {
        "1": 6,
        "2": 12,
        "3": 24
    }

    months = duration_map.get(choice, 6)
    start_date = datetime.now()
    end_date = start_date + timedelta(days=months * 30)

    member_id = len(memberships) + 1
    memberships[member_id] = {
        "Name": name,
        "Start": start_date,
        "End": end_date,
        "Status": "Active"
    }

    print(f"Membership added successfully. Membership Number: {member_id}")

def update_membership():
    try:
        member_id = int(input("Enter Membership Number: "))
    except:
        print("Invalid Membership Number")
        return

    if member_id not in memberships:
        print("Membership not found")
        return

    member = memberships[member_id]
    print("Member Found:", member)

    print("1. Extend Membership (Default 6 months)")
    print("2. Cancel Membership")

    choice = input("Choice: ") or "1"

    if choice == "1":
        member["End"] += timedelta(days=180)
        print("Membership extended by 6 months")
    elif choice == "2":
        member["Status"] = "Cancelled"
        print("Membership cancelled")

def view_reports():
    print("\n--- Membership Report ---")
    if not memberships:
        print("No records found")
        return

    for k, v in memberships.items():
        print(f"ID:{k} | {v['Name']} | Status:{v['Status']} |Valid Till:{v['End'].date()}")

def view_transactions():
    print("\n--- Transactions ---")
    for k, v in memberships.items():
        print(f"Membership {k} -> {v['Status']}")

def admin_menu():
    while True:
        print("""
--- ADMIN MENU ---
1. Add Membership
2. Update Membership
3. Reports
4. Transactions
0. Logout
""")
        ch = input("Choice: ")

        if ch == "1":
            add_membership()
        elif ch == "2":
            update_membership()
        elif ch == "3":
            view_reports()
        elif ch == "4":
            view_transactions()
        elif ch == "0":
            clear_session()
            break

def user_menu():
    while True:
        print("""
--- USER MENU ---
1. View Reports
2. View Transactions
0. Logout
""")
        ch = input("Choice: ")

        if ch == "1":
            view_reports()
        elif ch == "2":
            view_transactions()
        elif ch == "0":
            clear_session()
            break

while True:
    print("""
--- EVENT MANAGEMENT SYSTEM ---
1. Admin Login
2. User Signup
3. User Login
0. Exit
""")
    choice = input("Choice: ")

    if choice == "1":
        admin_login()
        if require_login("admin"):
            admin_menu()

    elif choice == "2":
        user_signup()

    elif choice == "3":
        user_login()
        if require_login("user"):
            user_menu()

    elif choice == "0":
        print("Exiting application")
        break
