# -*- coding: utf-8 -*-
"""Technical Event Management.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KlXhHezOr4G8WXQyjxF9X3uUftFLfOl7
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_excel("Technical Event Management 1.xlsx")
print("Excel loaded successfully")
print(df.head())

# DATA STORAGE (in-memory)
admins = {}
vendors = {}
users = {}
products = []
cart = []
orders = []

# AUTH FUNCTIONS
def admin_signup():
    u = input("Admin Username: ")
    p = input("Password: ")
    admins[u] = p
    print("Admin Registered Successfully")

def admin_login():
    u = input("Username: ")
    p = input("Password: ")
    return admins.get(u) == p

def vendor_signup():
    u = input("Vendor Username: ")
    p = input("Password: ")
    vendors[u] = p
    print("Vendor Registered")

def vendor_login():
    u = input("Vendor Username: ")
    p = input("Password: ")
    return u if vendors.get(u) == p else None

def user_signup():
    u = input("User Username: ")
    p = input("Password: ")
    users[u] = p
    print("User Registered")

def user_login():
    u = input("Username: ")
    p = input("Password: ")
    return u if users.get(u) == p else None

# VENDOR FUNCTIONS

def add_product(vendor):
    name = input("Product Name: ")
    price = float(input("Price: "))
    products.append({
        "Vendor": vendor,
        "Product": name,
        "Price": price
    })
    print("Product Added")

# USER FUNCTIONS

def view_products():
    if not products:
        print("No Products Available")
        return
    df = pd.DataFrame(products)
    print(df)

def add_to_cart(user):
    view_products()
    name = input("Enter product name to add: ")
    for p in products:
        if p["Product"] == name:
            cart.append({"User": user, **p})
            print("Added to Cart")
            return
    print("Product not found")

def checkout(user):
    user_cart = [c for c in cart if c["User"] == user]
    if not user_cart:
        print("Cart Empty")
        return
    total = sum(item["Price"] for item in user_cart)
    orders.append({"User": user, "Total": total, "Status": "Placed"})
    print("Order Placed | Total =", total)

# ADMIN VIEW

def admin_panel():
    print("\nUSERS:", users)
    print("VENDORS:", vendors)
    print("PRODUCTS:")
    if products:
        print(pd.DataFrame(products))
    print("ORDERS:")
    if orders:
        print(pd.DataFrame(orders))

# MAIN MENU

while True:
    print("""
1. Admin Signup
2. Admin Login
3. Vendor Signup
4. Vendor Login
5. User Signup
6. User Login
0. Exit
""")
    ch = input("Choice: ")

    if ch == "1":
        admin_signup()

    elif ch == "2":
        if admin_login():
            admin_panel()
        else:
            print("Invalid Admin Login")

    elif ch == "3":
        vendor_signup()

    elif ch == "4":
        v = vendor_login()
        if v:
            add_product(v)
        else:
            print("Vendor Login Failed")

    elif ch == "5":
        user_signup()

    elif ch == "6":
        u = user_login()
        if u:
            while True:
                print("""
1. View Products
2. Add to Cart
3. Checkout
0. Logout
""")
                c = input("Choice: ")
                if c == "1":
                    view_products()
                elif c == "2":
                    add_to_cart(u)
                elif c == "3":
                    checkout(u)
                elif c == "0":
                    break
        else:
            print("User Login Failed")

    elif ch == "0":
        break
